#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DP-1 -d 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus none
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config normal_border_color "#1d2021"
bspc config active_border_color "#1d2021"
bspc config focused_border_color "#ea6962"
bspc config presel_feedback_color "#ea6962"

feh --bg-center $HOME/Pictures/Wallpapers/statue.png --bg-center $HOME/Pictures/Wallpapers/statue.png &
$HOME/.config/polybar/launch.sh
picom &
dunst &

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
